services:
  - type: web
    name: study-hub
    env: python
    plan: starter
    buildCommand: |
      chmod +x build.sh
      ./build.sh
    startCommand: |
      cd backend
      flask db upgrade
      gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_APP
        value: app.py
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: study-hub-db
          property: connectionString
    databases:
      - name: study-hub-db
        databaseName: studyhub
        user: studyhub 