"""Add date_enrolled to Enrollment

Revision ID: c6329b885de8
Revises: 35c33d45de1a
Create Date: 2025-06-26 17:51:03.810744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6329b885de8'
down_revision = '35c33d45de1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_enrolled', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_column('date_enrolled')

    # ### end Alembic commands ###
